[package]
name = "windows_rogue_dhcp"
version = "0.1.0"
authors = ["Luke Hackworth <luke@lhackworth.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipconfig = "0.2.2"
